#!/bin/bash

set -euxo pipefail

SCRIPTDIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))

LAYERS=""

setup_profile() {
(
PROFILE=$1
PROFILEFILE=${SCRIPTDIR}/profiles/$(basename ${PROFILE} .conf).conf
PROFILENAME=$(basename ${PROFILEFILE} .conf)
CMD=""
DISTRO="poky"

. ${PROFILEFILE}

set +u
. ${SCRIPTDIR}/src/poky/oe-init-build-env ${SCRIPTDIR}-build-${PROFILENAME}
set -u

cat >bbwrapper.conf <<EOF
# this file is generated by setup_profile.sh, changes to this file will be overwritten

${CONFIG:-}

MACHINE="${MACHINE}"
DISTRO="${DISTRO}"
EOF

cat >yoctoenv.sh <<EOF
#!/bin/bash

# this file is generated by setup_profile.sh, changes to this file will be overwritten

export MACHINE=${MACHINE}
export DISTRO=${DISTRO}
. ${SCRIPTDIR}/src/poky/oe-init-build-env ${SCRIPTDIR}-build-${PROFILENAME}
cd \$OLDPWD
set -x
exec "\$@"
EOF
chmod +x yoctoenv.sh

cat >bbwrapper.sh <<EOF
#!/bin/bash

# this file is generated by setup_profile.sh, changes to this file will be overwritten

. ${SCRIPTDIR}/src/poky/oe-init-build-env ${SCRIPTDIR}-build-${PROFILENAME}
cd \$OLDPWD
set -x
exec bitbake -r ${PWD}/bbwrapper.conf "\$@"
EOF
chmod +x bbwrapper.sh


if [[ ! -e "downloads" ]]; then
ln -sf $HOME/.yoctocache/downloads
fi
if [[ ! -e "sstate-cache" ]]; then
ln -sf $HOME/.yoctocache/sstate-cache
fi

#echo $LAYERS
#cd ${SCRIPTDIR}/src
#ls
#echo $LAYERS | xargs -n1 readlink -f
#exit

if [[ "$LAYERS" ]]; then
bitbake-layers add-layer --force $(cd ${SCRIPTDIR}/src; echo $LAYERS | xargs readlink -f)
fi

)
}

setup_profile test-genericx86-64.conf
